### ISSUE TITLE
Support for garden's CSS-combiners syntax

### ISSUE THREAD

**Issue by TimovanderKamp** [untangled-web/om-css#8]
Currently no support for garden's CSS-combiners syntax '+' '>' '-' and '$'.

This:
`[:.a {..}`
`  [:+.b {..}]]`

Currently turns out as the following CSS:
`.ns_Component__a {`
` ... `
`}`
` `
`.ns_Component__a + .b {`
` ... `
`}`

It should turn out as:
`.ns_Component__a {`
` ... `
`}`
` `
`.ns_Component__a + .ns_Component__b {`
` ... `
`}`

**Comment by awkay** [comment]
Will also need a `$` variant for when you actually mean `+ .b` (global)
